In [ ]:
# This notebook analyzes the efficacy of different clustering algorithms for matching design patterns and design problems.
# Note: Table C2 in Hussain et al 2017 seems to indicate that fuzzy c-means clustering with binary weighting is the most effective combination for GoF patterns,
# but TF-IDF yields the highest f-value for fuzzy c-means (0.73).
# We are aiming for an f-value of 0.7 or above.

!pip install unidecode
!pip install fuzzy-c-means
!pip install --upgrade scikit-learn
!pip install scikit-learn-extra

from fcmeans                          import FCM

# Data Structures
import numpy  as np
import pandas as pd
import json
# Corpus Processing
import re
import nltk
import nltk.corpus
from nltk.tokenize                    import word_tokenize
from nltk.stem                        import WordNetLemmatizer
from nltk                             import SnowballStemmer, PorterStemmer
from nltk.tag                         import pos_tag

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('universal_tagset')

from sklearn.feature_extraction.text  import TfidfVectorizer, CountVectorizer
from sklearn.preprocessing            import normalize, Normalizer
from sklearn.decomposition            import PCA, TruncatedSVD
from sklearn.cluster                  import KMeans, BisectingKMeans, AgglomerativeClustering #, OPTICS
from sklearn_extra.cluster            import KMedoids
from sklearn.pipeline                 import make_pipeline

from unidecode                        import unidecode

# K-Means
from sklearn                          import cluster

# Visualization and Analysis
import matplotlib.pyplot  as plt
import matplotlib.cm      as cm
import seaborn            as sns
from sklearn.metrics                  import silhouette_samples, silhouette_score, confusion_matrix, ConfusionMatrixDisplay, f1_score
from wordcloud                        import WordCloud

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Package universal_tagset is already up-to-date!


In [137]:

def getTrainData(fileName):
  df = pd.read_csv(fileName)
  df = df.drop_duplicates(subset=['name'])
  return df

In [138]:
# Add the design problem to the dataset.
#problemRow = {'name':"bridge design problem 1", 'correct_category':1, 'overview':"Design a system enabling to display on a screen some empty windows (no button, no menu…). A window can have several different styles depending on the platform used. We consider two platforms, XWindow and Presentation Manager. The client code must be written independently and without knowledge of the future execution platform. It is probable that the system evolves in order to display specialized windows by ‘application windows’ (able to manage applications) and ‘iconised windows’ (with an icon)"}
#problemRow = {'name':"state design problem 2", 'correct_category':0,  'overview':"Design a DVD market place work. The DVD marketplace provides DVD to its clients with three categories: children, normal and new. A DVD is new during some weeks, and after change category. The DVD price depends on the category. It is probable that the system evolves in order to take into account the horror category"}
#problemRow = {'name':"mediator design problem 3", 'correct_category':0,  'overview':"Design the communications of a plane approaching an airport. When a plane approaches an airport, it must announce to all the other planes which are around that it intends to land, and await their confirmation before carrying out the operation. It is the control tower of the airport which guarantees the regulation of the air traffic, by making sure that there is no trajectory or destination conflict between several planes. In addition to the class diagram, you must also submit a collaboration (in the form of a diagram of collaboration or a diagram of objects and sequence) that describes the landing of a plane amidst in a context of two demands to land and one wanting to take off"}
#problemRow = {'name':"composite design problem 4", 'correct_category':1, 'overview':"Design a system enabling you to draw a graphic image. A graphic image is composed of lines, rectangles, texts, and images. An image may be composed of other images, lines, rectangles, and texts"}
#problemRow = {'name':"decorator design problem 5", 'correct_category':1, 'overview':"Design a system enabling you to display visual objects on a screen. A visual object can be composed of one or more texts or images. If needed, the system must allow the addition of a vertical scroll bar, a horizontal scroll bar, an edge and a menu to this object. These additions may be accumulated."}
#problemRow = {'name':"chain of responsbility design problem 6", 'correct_category':0, 'overview':"Design a help manager for a Java application. A help manager allows the display of a help message depending on the objects on which a client has clicked. For example, the “?”, sometimes located near the contextual menu of a Windows dialog box, allows the display of the help related to the button or the area where to click. If the button on which one clicks does not contain help, it is the area container which displays its help, and so on. If any object contains help, the help manager displays /“No help available for this area/”. Instantiate your class diagram in a sequence diagram of the example of a printing window. This window (JDialog) consists in an explanatory text (JLabel) and in a container (JPanel). This last contains a /“Print button/” (JButton) and a /“Cancel button/” (JButton). The /“Print button/” contains help /“Launches the impression of the document/”. The /“Cancel button/” the text as well as the window do not contain help. Lastly, the container contains help /“Click on one of the buttons/”. In the sequence diagram, reveal the scenarios: /“The user asks for the help of the Print button/”, /“the user asks for the help of the Cancel button/”, and /“the user asks for the help of the text/”"}
#problemRow = {'name':"command design problem 7", 'correct_category':0, 'overview':"Design a tutorial to learn how to program a calculator. This calculator executes the four basic arithmetic operations. The goal of this tutorial is to make it possible to take a set of operations to be executed sequentially. The tutorial presents a button for each arithmetic operation, and two input fields for the operands. After each click on a button of an operation, the user has then the choice to start again or execute the sequence of operations to obtain the result. It is probable that this tutorial evolves in order to make it possible for the user to remove the last operation of the list and to take into account the operation of modulo"}
#problemRow = {'name':"visitor design problem 8", 'correct_category':0, 'overview':"Many distinct and unrelated operations need to be performed on node objects in a heterogeneous aggregate structure. You want to avoid ‘polluting’ the node classes with these operations. And, you don't want to have to query the type of each node and cast the pointer to the correct type before performing the desired operation."}
#problemRow = {'name':"adapter design problem 9", 'correct_category':1, 'overview':"Design a drawing editor. A design is composed of te graphics (lines, rectangles and roses), positioned at precise positions. Each graphic form must be modeled by a class that provides a method draw(): void. A rose is a complex graphic designed by a black-box class component. This component performs this drawing in memory, and provides access through a method getRose(): int that returns the address of the drawing. It is probable that the system evolves in order to draw circles"}
# TODO: we need some design problems related to creational patterns
#df = df.append(problemRow, ignore_index=True)


In [139]:
# removes a list of words (ie. stopwords) from a tokenized list.
def removeWords(listOfTokens, listOfWords):
    return [token for token in listOfTokens if token not in listOfWords]

# applies stemming to a list of tokenized words
def applyStemming(listOfTokens, stemmer):
    return [stemmer.stem(token) for token in listOfTokens]

# applied lemmatization to a list of tokenized words
def applyLemmatization(listOfTokens, lemmatizer):
    return [lemmatizer.lemmatize(token) for token in listOfTokens]

# removes any words composed of less than 2 or more than 21 letters
def twoLetters(listOfTokens):
    twoLetterWord = []
    for token in listOfTokens:
        if len(token) <= 2 or len(token) >= 21:
            twoLetterWord.append(token)
    return twoLetterWord

# removes any words that aren't verbs
def notVerbs(listOfTokens):
    notVerb = []
    for token in listOfTokens:
        if pos_tag(word_tokenize(token), tagset="universal")[0][1] != "VERB":
            notVerb.append(token)
    return notVerb

In [140]:
def processCorpus(corpus, language, stemmer, lemmatizer):   
    stopwords = nltk.corpus.stopwords.words(language)
    param_stemmer = stemmer
    
    for document in corpus:
        index = corpus.index(document)
        corpus[index] = str(corpus[index]).replace(u'\ufffd', '8')   # Replaces the ASCII '�' symbol with '8'
        corpus[index] = corpus[index].replace(',', '')          # Removes commas
        corpus[index] = corpus[index].rstrip('\n')              # Removes line breaks
        corpus[index] = corpus[index].casefold()                # Makes all letters lowercase
        
        corpus[index] = re.sub('\W_',' ', corpus[index])        # removes specials characters and leaves only words
        corpus[index] = re.sub("\S*\d\S*"," ", corpus[index])   # removes numbers and words concatenated with numbers IE h4ck3r. Removes road names such as BR-381.
        corpus[index] = re.sub("\S*@\S*\s?"," ", corpus[index]) # removes emails and mentions (words with @)
        corpus[index] = re.sub(r'http\S+', '', corpus[index])   # removes URLs with http
        corpus[index] = re.sub(r'www\S+', '', corpus[index])    # removes URLs with www

        listOfTokens = word_tokenize(corpus[index])
        twoLetterWord = twoLetters(listOfTokens)
        notVerb = notVerbs(listOfTokens)

        listOfTokens = removeWords(listOfTokens, stopwords)
        listOfTokens = removeWords(listOfTokens, twoLetterWord)
        listOfTokens = removeWords(listOfTokens, notVerb)
        
        listOfTokens = applyStemming(listOfTokens, param_stemmer)
        #listOfTokens = applyLemmatization(listOfTokens, lemmatizer)

        corpus[index]   = " ".join(listOfTokens)
        corpus[index] = unidecode(corpus[index])

    return corpus

In [141]:
# TODO: use k-means before this chunk of code to classify the problem with a pattern class, then perform cosine similarity with the problem and the list of candidate patterns from that class.
# Source: https://danielcaraway.github.io/html/sklearn_cosine_similarity.html

def cosine_sim(df, df_col, class_no, pos_to_last):
  unigram_count = CountVectorizer(encoding='latin-1', binary=False)
  unigram_count_stop_remove = CountVectorizer(encoding='latin-1', binary=False, stop_words='english')

  # get the list of candidate patterns
  txts = df_col.loc[df['Kmeans'] == class_no] # where label == class_no
  vecs = unigram_count.fit_transform(txts)
  
  cos_sim = cosine_similarity(vecs[-pos_to_last], vecs)
  #sim_sorted_doc_idx = cos_sim.argsort()
  # print the most similar pattern to the problem; it's actually the problem itself
  #print("Design Problem: \n" + txts.iloc[sim_sorted_doc_idx[-1][len(txts)-1]] + "\n")

  #bestFittingPatternDesc = txts.iloc[sim_sorted_doc_idx[-1][len(txts)-2]]

  # print the second most similar pattern; it's likely the best-fitting design pattern for the design problem
  #print(txts[sim_sorted_doc_idx[-1][len(txts)-2]])
  #print("\nCorrect Pattern: " + (df['name'][(df['overview'] == bestFittingPatternDesc)]).to_string(index=False) + "\n")

  return cos_sim, txts


In [142]:
def displayPredictions(cos_sim, txts, df):
  sim_sorted_doc_idx = cos_sim.argsort()
  for i in range(len(txts) - 1):
    patternDesc = txts.iloc[sim_sorted_doc_idx[-1][len(txts)-(i + 2)]]
    patternName = (df['name'][(df['overview'] == patternDesc)]).to_string(index=False)
    percentMatch = int((cos_sim[0][sim_sorted_doc_idx[-1][len(txts)-(i + 2)]]) * 100)
    print("{}th pattern:  {:<20}{}%  match".format(i+1, patternName, percentMatch))


In [143]:
def runAlgorithms(num_clusters, final_df, df):
  # bisecting_strategy{“biggest_inertia”, “largest_cluster”}, default=”biggest_inertia”
  final_df_array = final_df.to_numpy()

  Bi_Bisect = BisectingKMeans(n_clusters=num_clusters, bisecting_strategy="biggest_inertia")
  Lc_Bisect = BisectingKMeans(n_clusters=num_clusters, bisecting_strategy="largest_cluster")
  Hierarchy = AgglomerativeClustering(n_clusters=num_clusters)
  Fuzzy_Means = FCM(n_clusters=num_clusters)
  Fuzzy_Means.fit(final_df_array)
  kmed = KMedoids(n_clusters=num_clusters)
  kmed_manhattan = KMedoids(n_clusters=num_clusters,metric='manhattan')
  Kmeans = cluster.KMeans(n_clusters = num_clusters)
  # optics = cluster.OPTICS(min_samples=num_clusters)

  Kmeans_labels = Kmeans.fit_predict(final_df)
  fuzzy_labels = Fuzzy_Means.predict(final_df_array)
  bi_bisect_labels = Bi_Bisect.fit_predict(final_df)
  lc_bisect_labels = Lc_Bisect.fit_predict(final_df)  
  hierarchy_labels = Hierarchy.fit_predict(final_df)
  kmed_labels = kmed.fit_predict(final_df)
  kmed_man_labels = kmed_manhattan.fit_predict(final_df)
  # optics_labels = optics.fit_predict(final_df_array)

  df['Kmeans'] = Kmeans_labels
  df['fuzzy'] = fuzzy_labels
  df['hierarchy'] = hierarchy_labels
  df['Bi_Bisect'] = bi_bisect_labels  
  df['Lc_Bisect'] = lc_bisect_labels
  df['PAM-EUCLIDEAN'] = kmed_labels
  df['PAM-MANHATTAN'] = kmed_man_labels
  # df['OPTICS'] = optics_labels


In [144]:
def Silhouette(vector_data, cluster_labels):
  # range_n_clusters = [2, 3, 4, 5, 6, 7, 8, 9]
  #silhouette_avg = []
  # for num_clusters in range_n_clusters:
  #   # initialise kmeans
  #   kmeans = KMeans(n_clusters=num_clusters, n_init='auto')
  #   kmeans.fit(vector_data)
  #   cluster_labels = kmeans.labels_
    
    # silhouette score
    #silhouette_avg.append(silhouette_score(vector_data, cluster_labels))
  s_avg = silhouette_score(vector_data, cluster_labels)
  return s_avg
  # plt.plot(range_n_clusters,silhouette_avg,'bx-')

  # plt.xlabel('Values of K') 
  # plt.ylabel('Silhouette score') 
  # plt.title('Silhouette analysis For Optimal k')
  # plt.show()

In [145]:
def getFScore(labels, df):
  df2 = df.pivot_table(index = ['correct_category'], aggfunc ='size')

  num_of_creational = df2[2]
  num_of_structural = df2[1]
  num_of_behavioral = df2[0]

  true_1 = [0]*num_of_creational + [1]*num_of_structural + [2]*num_of_behavioral
  true_2 = [0]*num_of_creational + [2]*num_of_structural + [1]*num_of_behavioral
  true_3 = [1]*num_of_creational + [0]*num_of_structural + [2]*num_of_behavioral
  true_4 = [1]*num_of_creational + [2]*num_of_structural + [0]*num_of_behavioral
  true_5 = [2]*num_of_creational + [0]*num_of_structural + [1]*num_of_behavioral
  true_6 = [2]*num_of_creational + [1]*num_of_structural + [0]*num_of_behavioral

  #print('===========KMEANS===========')
  #print('Predicted labels:')
  #display(Kmeans_labels.tolist())

  fscores = [
      f1_score(true_1, labels.tolist(),average='micro'),
      f1_score(true_2, labels.tolist(),average='micro'),
      f1_score(true_3, labels.tolist(),average='micro'),
      f1_score(true_4, labels.tolist(),average='micro'),
      f1_score(true_5, labels.tolist(),average='micro'),
      f1_score(true_6, labels.tolist(),average='micro')
  ]

  km_best = np.around(max(fscores),3)
  #print('\nBest fscore is:', km_best, 'from true_' + str(np.argmax(fscores) + 1))
  #display(globals()['true_' + str(np.argmax(fscores) + 1)])
  return km_best

In [146]:
def validateInput(designProblem):
  numOfWords = len(designProblem.split())
  if (numOfWords < 30 or numOfWords > 120):
    return False
  return True

def main():
  language = 'english'
  stemmer = PorterStemmer()
  lemmatizer = WordNetLemmatizer()
  vectorizer = TfidfVectorizer(sublinear_tf=True)
  df = getTrainData("GOF Patterns (2.0).csv")

  while(True):
    # designProblem = input("Enter your design problem: \n")

    # if(not validateInput(designProblem)):
    #   print("Invalid input size! please try again. \n")
    #   continue

    # problemRow = {'name':"design problem", 'correct_category':4, 'overview': designProblem}
    # df = df.append(problemRow, ignore_index=True)

    corpus = df['overview'].tolist()
    corpus = processCorpus(corpus, language, stemmer, lemmatizer)

    print(corpus[12][0:270])

    X = vectorizer.fit_transform(corpus)
    tf_idf = pd.DataFrame(data = X.toarray(), columns=vectorizer.get_feature_names_out())

    #runAlgorithms(3, tf_idf, df)
    #cos_sim, txts = cosine_sim(df, df['overview'], df['Kmeans'].iloc[df.index[-1]], 1)
    #displayPredictions(cos_sim, txts, df)
    return df, tf_idf, #cos_sim, txts 

#df, cos_sim, txts, tfidf = main()
df, tfidf = main()


coupl give receiv consid obtain click provid select might organ accord handl provid known might give get pass made say issu ensur handl access may known ascertain specifi specifi receiv work authent must realiz must perform must implement suggest ad sanit notic ad repea


In [147]:
kmeans_silhouette_avg = []
kmeans_fscore_avg = []

fmeans_silhouette_avg = []
fmeans_fscore_avg = []

hier_silhouette_avg = []
hier_fscore_avg = []

# kmed_silhouette_avg = []
# kmed_fscore_avg = []

# kmed_man_silhouette_avg = []
# kmed_man_fscore_avg = []

# bi_bisect_silhouette_avg = []
# bi_bisect_fscore_avg = []

# lc_bisect_silhouette_avg = []
# lc_bisect_fscore_avg = []

# optics_silhouette_avg = []
# optics_fscore_avg = []

num_clusters = 3
final_df = tfidf
final_df_array = final_df.to_numpy()

Hierarchy = AgglomerativeClustering(n_clusters=num_clusters)
Fuzzy_Means = FCM(n_clusters=num_clusters, m=1.67, max_iter=270)
Kmeans = cluster.KMeans(n_clusters = num_clusters, n_init='auto', max_iter=339)
# Bi_Bisect = BisectingKMeans(n_clusters=num_clusters, bisecting_strategy="biggest_inertia")
# Lc_Bisect = BisectingKMeans(n_clusters=num_clusters, bisecting_strategy="largest_cluster")
# kmed = KMedoids(n_clusters=num_clusters)
# kmed_manhattan = KMedoids(n_clusters=num_clusters,metric='manhattan')
# optics = cluster.OPTICS(min_samples=num_clusters)

for i in range(40):
    Fuzzy_Means.fit(final_df_array)
    Kmeans_labels = Kmeans.fit_predict(final_df)
    fuzzy_labels = Fuzzy_Means.predict(final_df_array)
    hierarchy_labels = Hierarchy.fit_predict(final_df)
    # bi_bisect_labels = Bi_Bisect.fit_predict(final_df)
    # lc_bisect_labels = Lc_Bisect.fit_predict(final_df)  
    # kmed_labels = kmed.fit_predict(final_df)
    # kmed_man_labels = kmed_manhattan.fit_predict(final_df)
    # optics_labels = optics.fit_predict(final_df_array)

    kmeans_fscore_avg.append(getFScore(Kmeans_labels, df))
    kmeans_silhouette_avg.append(Silhouette(tfidf, Kmeans_labels))

    fmeans_fscore_avg.append(getFScore(fuzzy_labels, df))
    fmeans_silhouette_avg.append(Silhouette(tfidf, fuzzy_labels))

    hier_fscore_avg.append(getFScore(hierarchy_labels, df))
    hier_silhouette_avg.append(Silhouette(tfidf, hierarchy_labels))

    # kmed_fscore_avg.append(getFScore(kmed_labels, df))
    # kmed_silhouette_avg.append(Silhouette(tfidf, kmed_labels))

    # kmed_man_fscore_avg.append(getFScore(kmed_man_labels, df))
    # kmed_man_silhouette_avg.append(Silhouette(tfidf, kmed_man_labels))

    # bi_bisect_fscore_avg.append(getFScore(bi_bisect_labels, df))
    # bi_bisect_silhouette_avg.append(Silhouette(tfidf, bi_bisect_labels))

    # lc_bisect_fscore_avg.append(getFScore(lc_bisect_labels, df))
    # lc_bisect_silhouette_avg.append(Silhouette(tfidf, lc_bisect_labels))

    # optics_fscore_avg.append(getFScore(optics_labels, df))
    # optics_silhouette_avg.append(Silhouette(tfidf, optics_labels))

    print(fuzzy_labels)

print("\n===========kmeans===========\n")
print("Average f-score:           ", sum(kmeans_fscore_avg) / len(kmeans_fscore_avg))
print("Average silhouette score:  ", sum(kmeans_silhouette_avg) / len(kmeans_silhouette_avg))

print("\n===========fmeans===========\n")
print("Average f-score:           ", sum(fmeans_fscore_avg) / len(fmeans_fscore_avg))
print("Average silhouette score:  ", sum(fmeans_silhouette_avg) / len(fmeans_silhouette_avg))

print("\n=========hierarchy==========\n")
print("Average f-score:           ", sum(hier_fscore_avg) / len(hier_fscore_avg))
print("Average silhouette score:  ", sum(hier_silhouette_avg) / len(hier_silhouette_avg))

# print("\n============kmed============\n")
# print("Average f-score:           ", sum(kmed_fscore_avg) / len(kmed_fscore_avg))
# print("Average silhouette score:  ", sum(kmed_silhouette_avg) / len(kmed_silhouette_avg))

# print("\n==========kmed-man==========\n")
# print("Average f-score:           ", sum(kmed_man_fscore_avg) / len(kmed_man_fscore_avg))
# print("Average silhouette score:  ", sum(kmed_man_silhouette_avg) / len(kmed_man_silhouette_avg))

# print("\n=========bi-bisect==========\n")
# print("Average f-score:           ", sum(bi_bisect_fscore_avg) / len(bi_bisect_fscore_avg))
# print("Average silhouette score:  ", sum(bi_bisect_silhouette_avg) / len(bi_bisect_silhouette_avg))

# print("\n=========lc-bisect==========\n")
# print("Average f-score:           ", sum(lc_bisect_fscore_avg) / len(lc_bisect_fscore_avg))
# print("Average silhouette score:  ", sum(lc_bisect_silhouette_avg) / len(lc_bisect_silhouette_avg))

# print("\n===========optics===========\n")
# print("Average f-score:           ", sum(optics_fscore_avg) / len(optics_fscore_avg))
# print("Average silhouette score:  ", sum(optics_silhouette_avg) / len(optics_silhouette_avg))

[1 1 1 1 1 1 0 0 0 2 1 1 0 1 0 0 2 0 0 2 0 2 0]
[1 1 1 1 1 1 1 0 0 2 1 1 0 1 0 0 0 0 0 0 0 0 0]
[2 2 2 2 1 2 1 0 1 0 1 2 2 2 0 0 0 0 0 0 2 0 0]
[2 2 2 2 2 2 0 1 1 1 2 2 0 2 1 1 1 1 1 1 1 2 1]
[1 0 1 1 1 1 2 2 2 1 1 0 2 0 2 2 1 2 2 2 2 1 2]
[1 1 1 1 1 1 2 2 2 1 1 1 2 0 2 2 2 2 2 2 2 1 2]
[2 1 2 2 1 1 0 0 0 1 2 2 2 2 0 0 0 0 0 0 0 2 0]
[0 0 0 0 0 0 2 2 2 1 0 0 2 2 2 2 1 1 2 2 2 0 2]
[1 1 1 1 1 1 1 0 2 2 1 1 0 1 0 0 0 2 0 0 0 0 0]
[0 0 0 0 0 0 0 2 2 1 0 0 2 1 1 1 1 1 1 1 2 2 1]
[2 2 2 2 2 2 2 1 1 2 2 2 1 1 0 0 2 0 0 0 1 1 0]
[2 2 2 2 2 2 1 0 1 0 2 2 1 1 0 0 0 0 0 0 1 2 0]
[2 2 2 2 2 2 2 1 0 0 2 2 0 2 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 1 2 2 2 0 0 2 0 2 2 2 2 2 2 2 1 2]
[0 0 0 0 0 0 0 2 2 2 0 0 1 1 2 2 2 2 2 2 1 2 2]
[2 2 2 2 2 2 0 0 0 2 2 2 0 2 1 0 1 0 1 1 0 1 0]
[2 2 2 2 2 2 1 0 1 2 2 2 0 2 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 2 1 0 0 2 0 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 2 2 2 1 0 1 2 2 2 2 2 2 2 2 2 0 2]
[0 0 0 0 0 0 0 2 2 1 0 0 2 0 2 2 1 2 2 2 2 2 2]
[2 2 2 2 2 2 1 0 0 0 2 2 0 2 0 0 0 0 0 0